name: Generate monochrome contribution graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: KertCainAbajo
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%23ffffff&color_dots=%23262626,%234a4a4a,%23737373,%23a6a6a6,%23ffffff
            dist/github-contribution-grid-snake.gif?color_snake=%23ffffff&color_dots=%23262626,%234a4a4a,%23737373,%23a6a6a6,%23ffffff&color_background=%230b0b0b

      - name: Publish contribution graph
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
